/**
 * Builds a branded, print-ready HTML report from report data + company profile.
 * Returns a full HTML string ready to inject into a print window.
 */
export function buildReportHTML({ companyProfile, reportTitle, reportPeriod, generatedBy, language, sections }) {
  const ci = companyProfile?.company_info || {};
  const primaryColor = ci.primary_color || '#1c2d5f';
  const locale = language === 'pt' ? 'pt-PT' : 'en-GB';
  const now = new Date();
  const dateStr = now.toLocaleDateString(locale, { day: '2-digit', month: 'long', year: 'numeric' });
  const timeStr = now.toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' });

  const escHtml = (str) => String(str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const sellerBlock = (ci.company_name || ci.logo_url) ? `
    <div class="seller-block">
      ${ci.logo_url ? `<img class="seller-logo" src="${ci.logo_url}" alt="Logo" />` : ''}
      <div class="seller-info">
        ${ci.company_name ? `<div class="company-name">${escHtml(ci.company_name)}</div>` : ''}
        ${ci.legal_name && ci.legal_name !== ci.company_name ? `<div class="company-sub">${escHtml(ci.legal_name)}</div>` : ''}
        ${ci.tax_number ? `<div class="company-sub">${language === 'pt' ? 'NIF' : 'Tax ID'}: ${escHtml(ci.tax_number)}</div>` : ''}
        ${ci.address ? `<div class="company-sub">${escHtml(ci.address)}</div>` : ''}
        <div class="company-sub contact-row">
          ${ci.phone ? `<span>${escHtml(ci.phone)}</span>` : ''}
          ${ci.email ? `<span>${escHtml(ci.email)}</span>` : ''}
          ${ci.website ? `<span>${escHtml(ci.website)}</span>` : ''}
        </div>
      </div>
    </div>` : '';

  const sectionsHTML = sections.map(section => {
    if (section.type === 'kpi-grid') {
      const items = section.items.map(item => `
        <div class="kpi-card">
          <div class="kpi-label">${escHtml(item.label)}</div>
          <div class="kpi-value">${escHtml(String(item.value))}</div>
          ${item.sub ? `<div class="kpi-sub">${escHtml(item.sub)}</div>` : ''}
        </div>`).join('');
      return `
        <div class="section">
          <h2 class="section-title">${escHtml(section.title)}</h2>
          <div class="kpi-grid">${items}</div>
        </div>`;
    }

    if (section.type === 'table') {
      const headerRow = section.columns.map(c => `<th>${escHtml(c.label)}</th>`).join('');
      const bodyRows = section.rows.map(row =>
        `<tr>${section.columns.map(c => `<td>${escHtml(String(row[c.key] ?? '—'))}</td>`).join('')}</tr>`
      ).join('');
      return `
        <div class="section">
          <h2 class="section-title">${escHtml(section.title)}</h2>
          ${section.subtitle ? `<p class="section-sub">${escHtml(section.subtitle)}</p>` : ''}
          <table>
            <thead><tr>${headerRow}</tr></thead>
            <tbody>${bodyRows || `<tr><td colspan="${section.columns.length}" style="text-align:center;color:#9ca3af">${language === 'pt' ? 'Sem dados' : 'No data'}</td></tr>`}</tbody>
          </table>
        </div>`;
    }

    if (section.type === 'stat-rows') {
      const rows = section.items.map(item => `
        <div class="stat-row">
          <span class="stat-label">${escHtml(item.label)}</span>
          <span class="stat-value ${item.highlight ? 'highlight' : ''}">${escHtml(String(item.value))}</span>
        </div>`).join('');
      return `
        <div class="section">
          <h2 class="section-title">${escHtml(section.title)}</h2>
          <div class="stat-rows">${rows}</div>
        </div>`;
    }

    return '';
  }).join('');

  return `<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escHtml(reportTitle)}</title>
  <style>
    @page {
      size: A4;
      margin: 18mm 16mm 22mm 16mm;
      @bottom-center {
        content: "${escHtml(ci.company_name || 'WiKima')} · ${escHtml(dateStr)} · " counter(page) " / " counter(pages) " · Generated by WiKima";
        font-size: 9px;
        color: #9ca3af;
      }
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #111827; background: #fff; font-size: 13px; }

    /* Seller / Company block */
    .seller-block { display: flex; align-items: flex-start; gap: 14px; padding-bottom: 18px; margin-bottom: 18px; border-bottom: 2px solid ${primaryColor}; }
    .seller-logo { max-height: 52px; max-width: 160px; object-fit: contain; flex-shrink: 0; }
    .seller-info .company-name { font-size: 18px; font-weight: 800; color: #111827; }
    .seller-info .company-sub { font-size: 11px; color: #6b7280; margin-top: 2px; }
    .seller-info .contact-row { display: flex; gap: 12px; margin-top: 3px; flex-wrap: wrap; }

    /* Report header band */
    .report-header { background: ${primaryColor}; color: #fff; border-radius: 8px; padding: 18px 22px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-start; }
    .report-header .report-title { font-size: 20px; font-weight: 900; letter-spacing: -0.3px; }
    .report-header .report-meta { font-size: 11px; color: rgba(255,255,255,0.75); margin-top: 4px; }
    .report-header-right { text-align: right; }
    .report-header-right .report-date { font-size: 12px; color: rgba(255,255,255,0.85); }
    .report-header-right .report-by { font-size: 11px; color: rgba(255,255,255,0.6); margin-top: 3px; }

    /* Sections */
    .section { margin-bottom: 24px; page-break-inside: avoid; }
    .section-title { font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: ${primaryColor}; margin-bottom: 10px; padding-bottom: 5px; border-bottom: 1px solid #e5e7eb; }
    .section-sub { font-size: 11px; color: #6b7280; margin-bottom: 8px; margin-top: -6px; }

    /* KPI grid */
    .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; }
    .kpi-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 14px; }
    .kpi-label { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #9ca3af; margin-bottom: 5px; }
    .kpi-value { font-size: 22px; font-weight: 900; color: #111827; }
    .kpi-sub { font-size: 10px; color: #6b7280; margin-top: 3px; }

    /* Tables */
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    thead tr { background: ${primaryColor}; color: #fff; }
    th { padding: 8px 10px; text-align: left; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; }
    td { padding: 7px 10px; border-bottom: 1px solid #f3f4f6; color: #374151; }
    tbody tr:nth-child(even) { background: #f9fafb; }
    tbody tr:last-child td { border-bottom: none; }

    /* Stat rows */
    .stat-rows { border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }
    .stat-row { display: flex; justify-content: space-between; align-items: center; padding: 9px 14px; border-bottom: 1px solid #f3f4f6; }
    .stat-row:last-child { border-bottom: none; }
    .stat-row:nth-child(even) { background: #f9fafb; }
    .stat-label { font-size: 12px; color: #6b7280; }
    .stat-value { font-size: 13px; font-weight: 700; color: #111827; }
    .stat-value.highlight { color: ${primaryColor}; }

    /* Footer */
    .report-footer { border-top: 1px solid #e5e7eb; padding-top: 12px; margin-top: 24px; display: flex; justify-content: space-between; align-items: center; font-size: 10px; color: #9ca3af; }
  </style>
</head>
<body>
  ${sellerBlock}

  <div class="report-header">
    <div>
      <div class="report-title">${escHtml(reportTitle)}</div>
      ${reportPeriod ? `<div class="report-meta">${escHtml(reportPeriod)}</div>` : ''}
    </div>
    <div class="report-header-right">
      <div class="report-date">${dateStr} ${timeStr}</div>
      ${generatedBy ? `<div class="report-by">${language === 'pt' ? 'Gerado por' : 'Generated by'}: ${escHtml(generatedBy)}</div>` : ''}
    </div>
  </div>

  ${sectionsHTML}

  <div class="report-footer">
    <span>${escHtml(ci.company_name || 'WiKima')} · ${escHtml(dateStr)}</span>
    <span>${language === 'pt' ? 'Gerado por WiKima' : 'Generated by WiKima'}</span>
  </div>
</body>
</html>`;
}

export function openPrintWindow(html) {
  const win = window.open('', '_blank', 'width=900,height=750');
  if (!win) return;
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.onload = () => { win.focus(); win.print(); };
}